### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by riher** [GSam/Capture2Text#1]
Tried for half an hour but I can't make it work. Could you add some instructions please?

**Comment by GSam** [comment]
I'm surprised anyone actually noticed this. Let me find some for you.

**Comment by GSam** [comment]
sudo apt-get install -y libtesseract-dev qtbase5-dev libleptonica-dev

./build-capture2text.sh

https://github.com/GSam/OCR-Pipelines/blob/master/build-capture2text.sh
I'll update the README.md later.

**Comment by GSam** [comment]
The English.zip is just a copy of the tesseract data from the original repo -- no idea where it's actually sourced from originally.

**Comment by riher** [comment]
Works like a charm, thanks!

**Comment by GSam** [comment]
Fixed the readme. Closing.

**Comment by sidvud98** [comment]
is it possible to use this on linux or only on windows and mac?
